### ISSUE TITLE
Imagekit Android not working in production (ProGuard)

### ISSUE THREAD

**Issue by JaleelNazir** [imagekit-developer/imagekit-android#37]
Issue 1:

ENOENT (No such file or directory)

This issue has been fixed by using the File upload method instead of Bitmap. Attached is the crashlytics file for reference.

Issue 2:

An unknown error. The upload is failing randomly without any exception. We discovered this through user reviews on the Play Store and analytics events.

Here is the additional information along with the sample code we have used:
```

minSdkVersion 24
targetSdkVersion: 34

Below are the library versions we are using:

// ImageKit.io SDK for profile pic update
implementation 'com.github.imagekit-developer:imagekit-android:3.0.1'

// Retrofit
implementation "com.squareup.okhttp3:okhttp:4.11.0"
implementation "com.squareup.okhttp3:logging-interceptor:4.9.0"
implementation "com.squareup.retrofit2:retrofit:2.9.0"
implementation "com.squareup.retrofit2:converter-gson:2.9.0"

```

// Code
```

private val filename: String = "pp.jpg"
private val folder: String = "/pp/"
private val useUniqueFileName: Boolean = true

val policy = UploadPolicy.Builder()
    .requireNetworkType(UploadPolicy.NetworkType.ANY)
    .maxRetries(3)
    .backoffCriteria(600000L, UploadPolicy.BackoffPolicy.EXPONENTIAL)
    .build()

ImageKit.getInstance().uploader().upload(
    file = file,
    token = authToken,
    fileName = filename,
    useUniqueFileName = this.useUniqueFileName,
    folder = folder,
    tags = arrayOf(""),
    policy = policy,
    imageKitCallback = object: ImageKitCallback {
        override fun onSuccess(uploadResponse: UploadResponse) {
            // Handle Success Response
            if (uploadResponse != null && uploadResponse.url != null) {
                // Handle Success Response
                updateImageUrlToServer(context, uploadResponse.url, image)
            }
        }

        override fun onError(uploadError: UploadError) {
            FirebaseCrashlytics.getInstance().log(uploadError.message)
        }
    }

```

Looks like the https://github.com/imagekit-developer/imagekit-android/issues/32 is not solved yet.

Attached is the proguard and crash file for reference. 

[crash_stacktrace.txt](https://github.com/user-attachments/files/16312668/crash_stacktrace.txt)

[proguard-rules.txt](https://github.com/user-attachments/files/16312658/proguard-rules.txt)

We already sent email regarding this, Could you please assist us in resolving these issues?

**Comment by ahnv** [comment]
Hey @JaleelNazir , 

### Issue 1

I was able to reproduce a similar errors at my end, the scenarios along with the errors are listed below

Scenario 1: When pp.jpg is a directory

Code:

```
val file = File(context.cacheDir, "pp.jpg")
file.mkdirs()
...
ImageKit.getInstance().uploader().upload(
      file = file,
...
```

Error:

```
2024-08-21 00:46:03.604  7276-7309  AndroidRuntime          com.example.uploadtesting            E  FATAL EXCEPTION: RxComputationThreadPool-1
Process: com.example.uploadtesting, PID: 7276
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: <https://github.com/ReactiveX/RxJava/wiki/What>'s-different-in-2.0#error-handling | java.io.FileNotFoundException: /data/user/0/com.example.uploadtesting/cache/pp: open failed: EISDIR (Is a directory)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:59)
	at io.reactivex.internal.operators.single.SingleTimer$TimerDisposable.run(SingleTimer.java:56)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: /data/user/0/com.example.uploadtesting/cache/pp: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
	at com.imagekit.android.retrofit.NetworkManager.getFileUploadCall(NetworkManager.kt:80)
	at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:52)
	at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:51)
	at com.imagekit.android.data.Repository.upload$lambda$0(Repository.kt:51)
	at com.imagekit.android.data.Repository.$r8$lambda$XKEPkuxSHKiCB52fBR0A_DMpzCI(Unknown Source:0)
	at com.imagekit.android.data.Repository$$ExternalSyntheticLambda0.accept(D8$$SyntheticClass:0)
	at io.reactivex.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
	at io.reactivex.internal.operators.single.SingleTimer$TimerDisposable.run(SingleTimer.java:56) 
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) 
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	at java.lang.Thread.run(Thread.java:1012) 
Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:564)
	at java.io.FileInputStream.<init>(FileInputStream.java:160) 
	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63) 
	at com.imagekit.android.retrofit.NetworkManager.getFileUploadCall(NetworkManager.kt:80) 
	at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:52) 
	at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:51) 
	at com.imagekit.android.data.Repository.upload$lambda$0(Repository.kt:51) 
	at com.imagekit.android.data.Repository.$r8$lambda$XKEPkuxSHKiCB52fBR0A_DMpzCI(Unknown Source:0) 
	at com.imagekit.android.data.Repository$$ExternalSyntheticLambda0.accept(D8$$SyntheticClass:0) 
	at io.reactivex.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56) 
	at io.reactivex.internal.operators.single.SingleTimer$TimerDisposable.run(SingleTimer.java:56) 
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) 
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	at java.lang.Thread.run(Thread.java:1012) 
```

Scenario 2: When pp.jpg is not readable

Code:

```
val file = File(context.cacheDir, "pp.jpg")
file.createNewFile()
file.setReadable(false)
...
ImageKit.getInstance().uploader().upload(
      file = file,
...
```

Error:

```
2024-08-21 01:09:50.523  9664-9728  AndroidRuntime          com.example.uploadtesting            E  FATAL EXCEPTION: RxComputationThreadPool-1
Process: com.example.uploadtesting, PID: 9664
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: <https://github.com/ReactiveX/RxJava/wiki/What>'s-different-in-2.0#error-handling | java.io.FileNotFoundException: /data/user/0/com.example.uploadtesting/cache/pp.jpg: open failed: EACCES (Permission denied)
    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
    at io.reactivex.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:59)
    at io.reactivex.internal.operators.single.SingleTimer$TimerDisposable.run(SingleTimer.java:56)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: /data/user/0/com.example.uploadtesting/cache/pp.jpg: open failed: EACCES (Permission denied)
    at libcore.io.IoBridge.open(IoBridge.java:574)
    at java.io.FileInputStream.<init>(FileInputStream.java:160)
    at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
    at com.imagekit.android.retrofit.NetworkManager.getFileUploadCall(NetworkManager.kt:80)
    at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:52)
    at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:51)
    at com.imagekit.android.data.Repository.upload$lambda$0(Repository.kt:51)
    at com.imagekit.android.data.Repository.$r8$lambda$XKEPkuxSHKiCB52fBR0A_DMpzCI(Unknown Source:0)
    at com.imagekit.android.data.Repository$$ExternalSyntheticLambda0.accept(D8$$SyntheticClass:0)
    at io.reactivex.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
    at io.reactivex.internal.operators.single.SingleTimer$TimerDisposable.run(SingleTimer.java:56) 
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) 
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
    at java.lang.Thread.run(Thread.java:1012) 
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
    at libcore.io.Linux.open(Native Method)
    at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
    at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7758)
    at libcore.io.IoBridge.open(IoBridge.java:560)
    at java.io.FileInputStream.<init>(FileInputStream.java:160) 
    at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63) 
    at com.imagekit.android.retrofit.NetworkManager.getFileUploadCall(NetworkManager.kt:80) 
    at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:52) 
    at com.imagekit.android.data.Repository$upload$1.invoke(Repository.kt:51) 
    at com.imagekit.android.data.Repository.upload$lambda$0(Repository.kt:51) 
    at com.imagekit.android.data.Repository.$r8$lambda$XKEPkuxSHKiCB52fBR0A_DMpzCI(Unknown Source:0) 
    at com.imagekit.android.data.Repository$$ExternalSyntheticLambda0.accept(D8$$SyntheticClass:0) 
    at io.reactivex.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56) 
    at io.reactivex.internal.operators.single.SingleTimer$TimerDisposable.run(SingleTimer.java:56) 
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) 
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
    at java.lang.Thread.run(Thread.java:1012) 
```

Scenario 3 : The file exists at the time [this code](https://github.com/imagekit-developer/imagekit-android/blob/4f14468a88a66f9ec11537b4286486d831934a1c/imagekit/src/main/java/com/imagekit/android/ImagekitUploader.kt#L162) is executed but the file was deleted by the time it reaches [this line](https://github.com/imagekit-developer/imagekit-android/blob/4f14468a88a66f9ec11537b4286486d831934a1c/imagekit/src/main/java/com/imagekit/android/retrofit/NetworkManager.kt#L80) where the file actually read

This wasn't reproduced but the reasoning for this is supported by the [android documentation](https://developer.android.com/training/data-storage/app-specific#internal-create-cache)

> Caution: When the device is low on internal storage space, Android may delete these cache files to recover space. So check for the existence of your cache files before reading them.

Recommendations from our side :

- You can check `file.exists()`, `file.canRead()`, `file.isFile` are true before calling the upload function. 
- You can handle these errors by using `RxJavaPlugins.setErrorHandler` mentioned in the link provided in the error message [https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling)
- Instead of using cache storage, use external storage in the app to save the temporary images before uploading, so android doesn't delete the images

### Issue 2
Based on the code you provided and some of the reviews found on the playstore listing, the user’s concerns are infinite loading of the file upload

You have configured exponential backoff with backoffMillis as 600000L which is 10 minutes
Formula used for the backoff is interval * 2^(n-1), so the retries would be as follows:

Retry 0: 600,000 * 2^0 = 600,000 milliseconds (10 minutes)

Retry 1: 600,000 * 2^1 = 1,200,000 milliseconds (20 minutes)

Retry 2: 600,000 * 2^2 = 2,400,000 milliseconds (40 minutes)

Recommendations from our side:

- Either use linear backoff
- or shorter backoffMillis

**Comment by AniVerma17** [comment]
@ahnv I recently reproduced the originally reported scenario in this issue (error:  _ENOENT (No such file or directory)_), by simulating the low storage conditions in an Android emulator while running the upload requests, with the upload policy configured for very long retry timeouts. This error was happening mostly in the retry attempts, if the app cache was cleared before the next retry invocation for the upload, which caused the SDK to try reading from a file that didn't exist anymore, hence throwing the _FileNotFoundException_.

The root cause for this issue lies in the fact that within the SDK, the file to upload is re-read from cache storage in every retry attempt (the file is copied to the app cache by the SDK for preprocessing etc. before upload). To mitigate this particular issue, we can modify the uploader methods to read the file only once (at the initial upload attempt) and keep its data in-memory to be reused in the retry attempts as per the upload policy. With this, the uploader would work fine across long-running retries even if the app cache is cleared, and would be more performant with the reduced number of disk I/O operations.

I have implemented and tested this solution locally, please advise if it is good enough to patch the SDK with.
